<a href="https://colab.research.google.com/github/Akshithaa25/DeepLearning/blob/main/Lab_2_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns
from sklearn.impute import SimpleImputer
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam, SGD
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import confusion_matrix, precision_recall_curve

In [ ]:
df=pd.read_csv('/content/fraudTest.csv')

In [ ]:
# https://keras.io/examples/structured_data/imbalanced_classification/

In [ ]:
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497.0,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1.371817e+09,33.986391,-81.200714,0.0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302.0,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1.371817e+09,39.450498,-109.960431,0.0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496.0,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1.371817e+09,40.495810,-74.196111,0.0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767.0,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1.371817e+09,28.812398,-80.883061,0.0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126.0,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1.371817e+09,44.959148,-85.884734,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345075,345075,2020-11-01 15:28:10,4683520018489354,"fraud_Weimann, Kuhic and Beahan",shopping_pos,1.52,Charles,Carrillo,M,17547 Stephen Turnpike Apt. 846,...,33.9143,-118.3493,93193.0,"Editor, magazine features",1995-04-19,3a3f5e91fe24f54c4a63c37e22c6a8f2,1.383320e+09,32.926035,-117.671927,0.0
345076,345076,2020-11-01 15:28:40,583699482621,fraud_Abbott-Steuber,personal_care,89.45,Jennifer,Jones,F,5572 Kelly Plains Apt. 952,...,44.3481,-89.1101,15426.0,"Engineer, civil (contracting)",1936-07-22,07b28f536105f26c1377e56ceae0e8e1,1.383320e+09,44.307031,-89.723661,0.0
345077,345077,2020-11-01 15:29:48,340953839692349,fraud_McCullough LLC,misc_pos,68.73,Tyler,Wright,M,615 Clarke Spring Apt. 172,...,42.5164,-82.9832,134056.0,"Doctor, hospital",1980-05-18,33d27fa6412882c65360be8fdc74d637,1.383320e+09,41.960769,-82.209293,0.0
345078,345078,2020-11-01 15:30:02,30487648872433,fraud_Morissette-Schaefer,personal_care,21.44,Stephanie,Crane,F,144 Martinez Curve,...,38.0970,-86.1723,350.0,Counsellor,1955-01-05,f3ea88afbf6700277418d0ccbf0c2be4,1.383320e+09,37.111461,-87.064939,0.0
345079,345079,2020-11-01 15:30:32,4393520897625,"fraud_Turcotte, McKenzie and Koss",entertainment,78.22,Charles,Rodriguez,M,240 Tracy Forge,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128200 entries, 0 to 128199
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             128200 non-null  int64
 1   trans_date_trans_time  128200 non-null  object
 2   cc_num                 128199 non-null  float64
 3   merchant               128199 non-null  object
 4   category               128199 non-null  object
 5   amt                    128199 non-null  float64
 6   first                  128199 non-null  object
 7   last                   128199 non-null  object
 8   gender                 128199 non-null  object
 9   street                 128199 non-null  object
 10  city                   128199 non-null  object
 11  state                  128199 non-null  object
 12  zip                    128199 non-null  float64
 13  lat                    128199 non-null  float64
 14  long                   128199 non-null  float64
 15  city_pop               128199 non-null  float64
 16  job                    128199 non-null  object
 17  dob                    128199 non-null  object
 18  trans_num              128199 non-null  object
 19  unix_time              128199 non-null  float64
 20  merch_lat              128199 non-null  float64
 21  merch_long             128199 non-null  float64
 22  is_fraud               128199 non-null  float64
dtypes: float64(10), int64(1), object(12)
memory usage: 22.5+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   1
merchant                 1
category                 1
amt                      1
first                    1
last                     1
gender                   1
street                   1
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 1
job                      1
dob                      1
trans_num                1
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 1
dtype: int64

In [ ]:
numerical_features = ['amt', 'city_pop']
categorical_features = ['trans_date_trans_time', 'merchant', 'category', 'first', 'last', 'gender', 'street', 'city', 'state', 'job', 'dob']

In [ ]:
scaler = StandardScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])

In [ ]:
#Handling Missing Values
imputer = SimpleImputer(strategy='mean')
df[numerical_features] = imputer.fit_transform(df[numerical_features])

In [ ]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     1
state                    1
zip                      1
lat                      1
long                     1
city_pop                 0
job                      1
dob                      1
trans_num                1
unix_time                1
merch_lat                1
merch_long               1
is_fraud                 1
dtype: int64

In [ ]:
# Encoding categorical features
categorical_features = ['is_fraud']
label_encoders = {}
for feature in categorical_features:
    label_encoders[feature] = LabelEncoder()
    df[feature] = label_encoders[feature].fit_transform(df[feature])

In [ ]:
# Splitting the dataset into training and testing
X = df.drop(['is_fraud', 'cc_num', 'trans_date_trans_time'], axis=1)
y = df['is_fraud']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compile the Model with different optimization algorithms and learning rates
optimizers = [Adam(learning_rate=0.001), SGD(learning_rate=0.01)]
for optimizer in optimizers:
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])